name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: create new dir
      run: mkdir ./doc
    - name: create new file
      run: touch ./doc/test1.txt
    - name: Pushes to another repository

      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'doc'
        destination-github-username: 'avi278'
        destination-repository-name: 'test1'
        target-branch: main
        target-directory: docss
        create-target-branch-if-needed: true
        commit-message: 'doc generating'