name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'test/'
        destination-github-username: 'avi278'
        destination-repository-name: 'test1'
        user-email: carles@pina.cat
        target-branch: main
        target-directory: docs