name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: echo ${{ secrets.API_TOKEN_GITHUB }}

    - name: build documentation
      run: touch _build/html/.nojekyll
    - name: Push
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: '_build/html'
        destination-github-username: 'avi278'
        destination-repository-name: 'test1'
        user-email: iva.utikiv@gmail.com
        target-branch: main
        target-directory: test