name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install typedoc
      run: npm install typedoc typedoc-plugin-markdown@next && typedoc --plugin typedoc-plugin-markdown --out docs src/index.ts
        

    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'doc'
        destination-github-username: 'avi278'
        destination-repository-name: 'test1'
        target-branch: main
        target-directory: docss
        create-target-branch-if-needed: true
        commit-message: 'doc generating'