name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes to another repository
      uses: vinayb21/github-action-push-to-another-repo@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: './test2.md'
        destination-github-username: 'avi278'
        destination-repository-name: 'test1'
        user-email: iva.utikiv@gmai.com