name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: './test/test2.md'
        destination_repo: 'avi278/test1'
        destination_folder: 'main'
        user_email: 'example@email.com'
        user_name: 'dmnemec'
        commit_message: 'A custom message for the commit'
